[[profiles]]
id = "msdos622"
name = "MSDOS 6.22"
image = { Iso = { url = "http://images.playground.flat.rs/DOS6.22_bootdisk.iso", sha256 = "c00f4612390689b1c6c4512177cce1cc3cbc7ad98c9bb8357e61529b0f19eb77" } }

[[profiles]]
id = "redox0-5-0"
name = "Redox OS 0.5.0"
image = { Iso = { url = "http://images.playground.flat.rs/redox_0.5.0_livedisk.iso", sha256 = "d45cb423dc9719f921076434424c524c0ba12778d6e8a90a729b66ee6846b66e" } }

[[profiles]]
id = "alpine-linux"
name = "Alpine Linux"
image = { Iso = { url = "http://images.playground.flat.rs/alpine-extended-3.11.3-x86_64.iso", sha256 = "35445abe9860b60d3e2288fd43ddb31af297246e13563e35b032f870cecda3bb" } }

[[profiles]]
id = "l4linux-demo-cd"
name = "L4Linux Demo CD"
image = { Iso = { url = "http://images.playground.flat.rs/l4linux-demo-cd-0-1.iso", sha256 = "e7786602e265ecac4bdec29cd9fd674f71a830e6e98c4938a58cf630b620b725" } }
