[[profiles]]
id = "linux-latest"
name = "Linux (Latest)"
image = { Multiboot = { kernel = { url = "http://images.playground.flat.rs/vmlinuz-5.3.0-29-generic", sha256 = "d8db09e53436bf874de149e03cf5e3d38af7426cc42123a7482a1820616e9cc1" }, ramdisk = { url = "http://images.playground.flat.rs/initrd.img-5.3.0-29-generic", sha256 = "96985db9f4dadc51091de7ef81153edb478e8bbba855d3e3dcea9b43b0aaf779" } } }
